### ISSUE TITLE
Add satellite to model

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-prediction#102]
Add eumetsat satellite to model

- First of all take 5 by 5 square around point and take mean
- use nohrv as it gives you 11 channels
- Do it in a similar way to the NWP data

Would be great if it can train from google dataset, 
in live inference, would work from the UK Sat-Consumer

**Comment by peterdudfield** [comment]
Hey jacob, do you have an easy way to convert between x_geostationary and y_geo to lat long, and the other way round? 

I saw in data pipes we can do it here - https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/utils/geospatial.py

For the big google satellite dataset, I couldnt find that attribute though. Do you know where to find that @jacobbieker

**Comment by jacobbieker** [comment]
The `area` attribute is in the DataArray in each of the Datasets. When datapipes loads the satellite data here: https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/load/satellite.py it takes out the DataArray, which contains that. The other option would be to do something like this to copy the attribute to the Dataset

```python
data = xr.open_zarr(/path/to/gcp/)
data.attr['area'] = data['data'].attr['area']
```

**Comment by peterdudfield** [comment]
> The `area` attribute is in the DataArray in each of the Datasets. When datapipes loads the satellite data here: https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/load/satellite.py it takes out the DataArray, which contains that. The other option would be to do something like this to copy the attribute to the Dataset
> 
> ```python
> data = xr.open_zarr(/path/to/gcp/)
> data.attr['area'] = data['data'].attr['area']
> ```

Thank you, this is perfect

**Comment by peterdudfield** [comment]
Thanks Jacob, would you be able to give me an example of a coordiante for London? Just so I can get the transformations right from lat lon?

**Comment by peterdudfield** [comment]
I'm looking at a picture, perahps its about 
x = -600,000
y = 460,000

**Comment by jacobbieker** [comment]
Sorry for the delay, here is the middle of London in geostationary:
x=-622532.3807857306 y=4622973.744668174

**Comment by peterdudfield** [comment]
No worries thanks

**Comment by peterdudfield** [comment]
For adding patches its slightly easier to take an area defined by degrees that the 5 closes pixels. I think area by degrees might infact be better. This amount can be changed in the config. 

Ive got for 0.25 degrees, @jacobbieker @dfulu @zakwatts thoughts?

**Comment by jacobbieker** [comment]
I would probably do a bit larger than 0.25 degrees, probably like 0.5 or even 1.0 degrees? That would correspond to around 50km-110km around the point, which would cover any large clouds that could come over the site in the next ~hour. But yeah, doing it by degrees instead of pixels seems good, since its being averaged anyway.

**Comment by jacobbieker** [comment]
Sounds good. The rough rule of thumb, based off of MetNet papers, is that clouds move at most around 64km per hour, so if we want to forecast to be able to see clouds that might come over it in the next hour, we need to look at least 64km away from it in all directions, hence why I think 1 degree would work better? But yeah, happy to see which one works best, and I do get it would also see clouds that are moving away from the site as well.

**Comment by peterdudfield** [comment]
> Sounds good. The rough rule of thumb, based off of MetNet papers, is that clouds move at most around 64km per hour, so if we want to forecast to be able to see clouds that might come over it in the next hour, we need to look at least 64km away from it in all directions, hence why I think 1 degree would work better? But yeah, happy to see which one works best, and I do get it would also see clouds that are moving away from the site as well.

yea but Metnet doesn't take an average of these patches. 

So perhaps the optimial for
- average patch could be 0.5
- all data points, could be 2 degrees

but we can find this all out in hyperparameters

**Comment by peterdudfield** [comment]
Ill close this for the moment, and add other small satellite tasks
