### ISSUE TITLE
Add CI testing

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-prediction#12]
As we move towards production, we should make sure tests run with every push

We've got a fairly standard way to do this at OCF. See example (here)[ https://github.com/openclimatefix/ocf_datapipes/blob/main/.github/workflows/workflows.yaml]
This will use a standard requiremtns.txt file though, it might be easier to add a rquirements file, rather than adjust it for `poetry`

**Comment by simlmx** [comment]
I started by simply running the linting and tests as defined in the repo.
See #24
