### ISSUE TITLE
Run backtest for 24342 and 25545

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-prediction#94]
Run a years worth of backtest for the sites 
24342 and 25545

**Comment by peterdudfield** [comment]
Note that the ss_id is `7044` and `27020`

**Comment by peterdudfield** [comment]
I ran 
```python3.10 psp/scripts/eval_model.py -r exp_results/ -n loop --eval-config=psp.exp_configs.uk_pv_prod --new-exp-name exp_results/trust/ --sequential --test-start='2021-01-01' --test-end='2021-10-01'```

Things that i needed to fix
- need to set step mintues to 15

**Comment by simlmx** [comment]
It seems the "help" for the `--sequential` argument is outdated:
https://github.com/openclimatefix/pv-site-prediction/blob/main/psp/scripts/eval_model.py#L72
and that the option is now in the `TestDateSplit` object:
https://github.com/openclimatefix/pv-site-prediction/blob/main/psp/scripts/eval_model.py#L152

You should be able to run every 15 minutes by passing `step_minutes=15` to the `TestDateSplit` object in the [`uk_pv_prod`][1] config!

[1]: https://github.com/openclimatefix/pv-site-prediction/blob/main/psp/exp_configs/uk_pv_prod.py#L242C29-L242C42

**Comment by peterdudfield** [comment]
Thanks @simlmx , yea I managed to find that, and got it running - thanks

**Comment by simlmx** [comment]
Awesome!

**Comment by peterdudfield** [comment]
Becasye 7704 doesnt have any live data anymore, it would be good to add another site like `27710`

**Comment by peterdudfield** [comment]
now ran `python3.10 psp/scripts/eval_model.py -r exp_results/ -n loop --eval-config=psp.exp_configs.uk_pv_prod --new-exp-name exp_results/trust/ --sequential --test-start='2022-01-01' --test-end='2023-01-01' --pv-ids='7044,27020'`
